cmake -DCMAKE_BUILD_TYPE=debug -DLLVM_ENABLE_PROJECTS=clang -DLLVM_USE_LINKER=gold -DLLVM_PARALLEL_LINK_JOBS=2 -DLLVM_OPTIMIZED_TABLEGEN=true -DLLVM_CCACHE_BUILD=true -G "Unix Makefiles" ../llvm
make
